### PR TITLE
Fix #14

### LINKED ISSUE #14: No visible setting change for dealing dealt cards onto canvas
I don't know if I'm stupid, but I can't find any settings for enabling cards that have been dealt to be placed onto the canvas. It says to look in settings, but I see no such setting for it in module settings for Card Tiles or Monk's Active Tile Triggers, and I don't see it in the settings for the canvas, decks, or cards.

Where can this be found and disabled? It makes it a lot more complicated if you can't just play a card from your hand by dragging it onto the canvas.

### PR DESCRIPTION
**Pull request by SalieriC**
This introduces the missing setting to allow placing already drawn cards on the canvas and sets the condition up with said setting, thus fixing #14.

### CODE REVIEW

**Comment by alessiocali** [comment]
I'll try to give it a look tomorrow, unfortunately I'm not following this project lately :(

**Comment by SalieriC** [comment]
Unfortunate. I wanted it for my upcoming game on Tuesday. Works fine as far as I can tell right now.

**Comment by alessiocali** [comment]
Ok I read again what I wrote and I realized old-me was idiotic enough to write a very poorly self-explanatory Warning message. What old-me meant was that "You cannot (ever!) pass to a stack a drawn card - if you want to deal on the canvas a drawn card, disable passing to a board stack."

That being said I see the point of adding an additional option. This way we can play on the canvas, and pass to board, only not-drawn cards, and drawn cards will be just played on the canvas (without changing their current stack).

I'd like this to  be clear in the setting's tooltip so I'll make some minor edits and push the commit.

**Comment by SalieriC** [comment]
So playing a card from hand to canvas would mean it would stay in the hand? If so, that seems pretty bad as in _different than real life_, which is always a ux concern for me. I'd rather suggest creating a canvas stack to which cards are passed when they are placed at the canvas. It would also open up a lot of flexibility for other features like picking up cards from the canvas and such.

**Comment by alessiocali** [comment]
I dug a bit more into it, I misinterpreted an error from Foundry. It's not that you cannot pass a drawn card to a stack - more specifically, you cannot pass a card, which is already played from a deck, from the same deck again.

In other words playing the same card twice on the canvas, from a single deck, while also passing it to the canvas board, would be forbidden, because that would create a duplicate card. However if you're moving from a hand, or a pile, to another hand or pile (or the canvas board) then that is perfectly allowed.

I'm jolting down a fix that makes this more explicit, allows to play on the canvas cards from other hands as  intended, and includes your fix so you can put on the canvas multiple tiles from the same deck if you really want to.

**Comment by SalieriC** [comment]
You've lost me a bit but I'm sure you'll come up with something functional. ^^'

**Comment by alessiocali** [comment]
Sorry :P To recap, in core Foundry, this won't work

* Deal from Deck D, Card C, to Pile P. C is now marked as "Drawn", but still visible in D.
* Deal again from D to P, or any other Pile: Forbidden! C is already Drawn, you cannot pull it from the deck again. You must move it out of P first.

However the following is perfectly legit:

* Deal from Deck D, Card C, to Hand H. C is now marked as "Drawn" and shows up in both D and H.
* Deal from H to Pile P. This is fine, even though C is "Drawn", you are just moving from a hand to a Pile. So there is no duplicate. 

So as long as we check against the card being drawn from a deck, it should be fine. I'll send you a PR to your branch to update this one soon. (GitHub works in mysterious ways, I can't just update this one for reviews).

**Comment by alessiocali** [comment]
Actually I can just open another PR to continue this one, that would be easier

**Comment by alessiocali** [comment]
Please refer to #17 - Let me know if you have some comments.

**Pull request closed without merging**
